services:
  db:
    image: postgres:16-alpine
    container_name: scrumforge-db
    environment:
      POSTGRES_USER: scrumforge
      POSTGRES_PASSWORD: scrumforge
      POSTGRES_DB: scrumforge
    ports:
      - "5440:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: scrumforge-backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "postgresql://scrumforge:scrumforge@db:5432/scrumforge?schema=public"
    depends_on:
      - db
    ports:
      - "4020:4020"

  frontend:
    build: ./frontend
    container_name: scrumforge-frontend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:4020"
    depends_on:
      - backend
    ports:
      - "3000:3000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: gourouvin.laurent@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
